.TH VCARD2QRCODE "1" "April 2022" "vcard2qrcode" "User commands"
.SH NAME
vcard2qrcode \- vcard to qrcode converter
.SH SYNOPSIS
.B vcard2qrcode [ -i | --input ]
.I vcard-filename.vcf
.B [ -o | --output ]
.I output-filename
.SH DESCRIPTION
.SH OPTIONS
.SH "EXIT STATUS"
.SH FILES
.SH EXAMPLES
.SH AUTHORS
.SH "REPORTING BUGS"
.SH COPYRIGHT
.SH "SEE ALSO"
