.TH VCARD2QRCODE "1" "April 2022" "vcard2qrcode" "User commands"
.SH NAME
vcard2qrcode \- vcard to qrcode converter
.SH SYNOPSIS
.B vcard2qrcode
.B [ -i | --input ]
.I vcard-filename.vcf
.B [ -o | --output ]
.I output-filename
.SH DESCRIPTION
.B vcard2qrcode
is a vcard to qrcode command line converter.
.SH OPTIONS
.SH "EXIT STATUS"
.TP
0
if OK,
.TP
1
if ERROR.
.SH FILES
.SH EXAMPLES
.SH AUTHORS
Written by Attila Zsolt Somogyi.
.SH "REPORTING BUGS"
.SH COPYRIGHT
.SH "SEE ALSO"
