#!/bin/sh
program_name=$0
usage(){
    echo "Usage: $program_name [ -i | --input FILENAME ] [ -o | --output FILENAME ]" 1>&2
}
exit_error(){
    usage
    exit 1
}
check_file(){
    input_file=$1
    if [ -f $input_file ]; then
        if [ -s $input_file ]; then
            if [ ! -r $input_file ]; then
                echo "$input_file file is not readable."
                exit_error
            fi
        else
            echo "$input_file file is empty."
            exit_error
        fi
    else
        echo "$input_file file is not exists."
        exit_error
    fi
}
check_vcard(){
    input_file=$1
    mime_type=$(file --brief --mime-type $input_file)
    if [ "$mime_type" != "text/vcard" ]; then
        echo "$input_file file is not vcard file."

    fi
}
number_of_arguments=$#
if [ $number_of_arguments -eq 0 ]; then
    exit_error
fi
short_options=i:,o:
long_options=input:,output:,
options=$(getopt --options $short_options --longoptions $long_options -- "$@")
eval set -- ${options}
while [ $# -gt 0 ]; do
    case "$1" in
        -i|--input)
            shift
            input_file=$1
            check_file $input_file
            check_vcard $input_file
            output_file_extension=svg
            output_file=$(dirname "$input_file")/${input_file%.*}
            ;;
        -o|--output)
            shift
            output_file=$1
            output_file_extension=${output_file##*.}
            output_file=$(dirname "$output_file")/${output_file%.*}
            ;;
        --)
            break
            ;;
        *)
            exit_error
            ;;
    esac
    shift
done
qrencode --read-from $input_file --type $output_file_extension --output $output_file.$output_file_extension
