#!/bin/sh
set -eu
name_of_the_current_shell_script=$0
program_name=vcard2qrcode
number_of_program_arguments=$#
program_arguments=$*
short_options=i:,o:,h
long_options=input:,output:,help
check_number_of_program_arguments(){
    if [ -z ${number_of_program_arguments+x} ]; then
        echo "number_of_program_arguments is not set." 1>&2
        exit_error
    elif [ "$number_of_program_arguments" -eq "$number_of_program_arguments" ] 2>/dev/null; then
        if [ $number_of_program_arguments -eq 0 ]; then
            exit_error
        fi
    else
        echo "number_of_program_arguments is not number." 1>&2
        exit_error
    fi
}
usage(){
    if [ -z ${program_name+x} ]; then
        echo "program_name is not set." 1>&2
        exit 1
    else
        echo "Usage: $program_name [ -i | --input FILENAME ] [ -o | --output FILENAME ]" 1>&2
    fi
}
exit_error(){
    usage
    exit 1
}
check_file(){
    if [ -z ${1+x} ]; then
        echo "Missing file argument on check_file() function." 1>&2
        exit_error
    else
        input_file=$1
    fi
    if [ -f "$input_file" ]; then
        if [ ! -r "$input_file" ]; then
            echo "$input_file file is not readable." 1>&2
            exit_error
        else
            if [ ! -s "$input_file" ]; then
                echo "$input_file file is empty." 1>&2
                exit_error
            fi
        fi
    else
        echo "$input_file file is not exists." 1>&2
        exit_error
    fi
}
check_vcard(){
    if [ -z ${1+x} ]; then
        echo "Missing file argument on check_vcard() function." 1>&2
        exit_error
    else
        input_file=$1
    fi
    check_file "$input_file"
    mime_type=$(file --brief --mime-type "$input_file")
    if [ "$mime_type" != "text/vcard" ]; then
        echo "$input_file file is not vcard file." 1>&2
        exit_error
    fi
}
main(){
    check_number_of_program_arguments
    options=$(getopt --options $short_options --longoptions $long_options --unquoted -- "$@")
    output_file=""
    eval set -- "${options}"
    while [ $# -gt 0 ]; do
        case "$1" in
            -i|--input)
                shift
                input_file=$1
                check_vcard "$input_file"
                ;;
            -o|--output)
                shift
                output_file=$1
                output_file_extension=${output_file##*.}
                output_file=$(dirname "$output_file")/${output_file%.*}
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            --)
                break
                ;;
            *)
                exit_error
                ;;
        esac
        shift
    done
    if [ -z "$input_file" ]; then
        exit_error
    fi
    if [ -z "$output_file" ]; then
        output_file_extension=svg
        output_file=$(dirname "$input_file")/${input_file%.*}
    fi
    qrencode --read-from "$input_file" --type "$output_file_extension" --output "$output_file.$output_file_extension"
}
if [ "$name_of_the_current_shell_script" != "/bin/sh" ]; then
    main "$program_arguments"
fi
